### ISSUE TITLE
RadioList on last Nette dev 2.1 - Notice – Undefined offset: 1

### ISSUE THREAD

**Issue by ghost** [Kdyby/BootstrapFormRenderer#15]
Problem is on line #512.
https://github.com/Kdyby/BootstrapFormRenderer/blob/master/src/Kdyby/BootstrapFormRenderer/BootstrapRenderer.php#L512

I hope, that report will be helpfull.

**Comment by fprochazka** [comment]
Yes, In actual master this is broken. 
https://twitter.com/Kdyby/status/327746564221202432

You can temporarily workaround it by fixing depenedencies to older commit.

**Comment by fprochazka** [comment]
This sould be fixed by now. Thank you for reporting :)
