### ISSUE TITLE
Radiolist: labels contain invalid class

### ISSUE THREAD

**Issue by stepansvoboda** [Kdyby/BootstrapFormRenderer#17]
The radio input labels rendered contain the invalid `control-label` class which causes the unwanted `text-align: right;` and breaks down the form layout as you can see on these attached screenshots:

![bootstrap2](https://f.cloud.github.com/assets/168612/597186/8028b7a0-cbe5-11e2-8cfb-13c0f404047d.png)

![bootstrap](https://f.cloud.github.com/assets/168612/597163/561c7b50-cbe4-11e2-9d2a-81091e496e8a.png)

After I have removed this class from the label the form seems to be just fine:

![bootstrap1](https://f.cloud.github.com/assets/168612/597180/150faa3c-cbe5-11e2-8e79-5ddd182ecf98.png)

As I hope this will be fixed as soon as possible I have realized this workaround:

```
$('input[type=radio]').parent().removeClass('control-label');
```

**Comment by fprochazka** [comment]
@rostenkowski hope this solves it, thank you for reporting :)

**Comment by stepansvoboda** [comment]
:+1: 

Confirmed. Thank you for such a fast action :)
