### ISSUE TITLE
Rendering modes: add support for modal forms

### ISSUE THREAD

**Issue by stepansvoboda** [Kdyby/BootstrapFormRenderer#19]
It would be nice to have the direct support for the [Bootstrap modals](http://twitter.github.io/bootstrap/javascript.html#modals). In other words this mode should wrap form controls into a `div.modal-body` and the form buttons into a `div.modal-footer` as you can see:

```
  <div class="modal-body">
    render form controls here...
  </div>
  <div class="modal-footer">
    render form buttons here...
  </div>
```

With this feature you will be able to do this:

```
<div class="modal hide">
  {form myModalForm}
</div>
```

AFAIK today this is possible using the great macros:

```
  <div class="modal-body">
    {form controls}
  </div>
  <div class="modal-footer">
    {input save}
  </div>
```

What do you think?

**Comment by fprochazka** [comment]
I'm not sure it would help that much. You can do that already this way

``` html
<div class="modal hide"> {form myModalForm}
  <div class="modal-body">
    {form controls}
  </div>
  <div class="modal-footer">
    {form buttons}
  </div>
{/form}</div>
```

Your way would mean a lot of configuration options. When I work with modals, this is never enough.

**Comment by stepansvoboda** [comment]
Yeah! I've found that way soon after... 

Only note: your way with `... {form buttons} ...` is not good because style of **`modal-footer` vs. `form-actions`**.
