### ISSUE TITLE
Support Twitter Bootstrap 3.0

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/BootstrapFormRenderer#20]

**Comment by motorcb** [comment]
When will this expansion take place?

**Comment by fprochazka** [comment]
Honestly, I have no idea.

On second thought, I'm more likely to create new extension for entire TwitterBootstrap for Nette, that would be more practical I think.

**Comment by rikiless** [comment]
Today RC2 was released with amount of changes in forms from RC1. Perhaps it would be appropriate to wait for final release (which should be released on 19.8).

**Comment by rikiless** [comment]
@HosipLan I think it would be better to release it as update and tagged. For example Bootstrap 2.3.2 and 3.0.0 isn't separated to two repositories. The question is if there are plans to support and making updates to form renderer for bootstrap 2.3.2.

**Comment by mishak87** [comment]
@rikiless only problem is how to version own library and its own changes when that library is based single resource that is being developed. AFAIK there is no solution for semantic versioning library like that. And even between Bootstrap 2.3.\* were some minor changes in markup so following new versions can be bit annoying.

Release cycle of bootstrap is nearly yearly (current release is 9 months or so) so I would be for branches per major version of Bootstrap.

_Also having bower.json with marked specific bootstrap version it is compatible with would be helpful._

**Comment by JanMikes** [comment]
@HosipLan Any progress? Im really looking forward

**Comment by Ciki** [comment]
@HosipLan Is it in or completely out of your focus? :)

**Comment by fprochazka** [comment]
I'm sorry to tell, but right now It couldn't have been any more out of my focus :)

**Comment by ghost** [comment]
But plase make it as new branch. :) Because I am & I will be using bootstrap 2.

**Comment by fprochazka** [comment]
@phoutedr I will do my best to keep compatibility both ways.

**Comment by karelbilek** [comment]
._ .

**Comment by fprochazka** [comment]
Hmm... https://github.com/nette/examples/blob/master/Forms/bootstrap3-rendering.php

**Comment by karelbilek** [comment]
How was I supposed to find that? :)

(I was searching in documentation and no mention anywhere. I wrote my own renderer instead.... oh well. At least I learned stuff.)

**Comment by karelbilek** [comment]
...well, my own renderer is almost exactly the same as what's in the examples, evidently. All right. :) At least it's linked here for the future

**Comment by fprochazka** [comment]
Well it's quite new (2.1 and 2.2-dev only)
