### ISSUE TITLE
Abstract base and split to another package.

### ISSUE THREAD

**Issue by mishak87** [Kdyby/BootstrapFormRenderer#33]
I get that it is small library already. Abstracting would help others (read me) with implementing own renderers for other frameworks (read Semantic UI) while using same scaffolding (read macros) in project (enabling drop in replacement of renderer).

BootstrapFormRenderer (@*.latte, actual renderer, small DI), FormRendererBase (Latte, DI, Interface)

DI of BaseFormRenderer could provide repository like interface for having multiple renderers in one project (usually just one with highest priority or per template).

**Comment by mishak87** [comment]
This could actually solve [Bootstrap 3](https://github.com/Kdyby/BootstrapFormRenderer/issues/20) issue because you could let it go.

**Comment by fprochazka** [comment]
I don't see why should I support BS3 if new nette forms are almost capable of supporting it.

Better would be to add that one tiny bit of missing functionality to Nette.
