### ISSUE TITLE
nette 2.2b compatibility

### ISSUE THREAD

**Issue by B4nan** [Kdyby/BootstrapFormRenderer#34]
kdyz renderuju formular pomoci {form name} ... {/form} tak se pouzije vychozi macro z nette, a v sablone se nevytvori promenna $__form -> nefunguji dalsi macra jako napriklad {pair name}

**Comment by fprochazka** [comment]
Nemyslím si, že je dobrý nápad upravovat renderer pro Nette 2.2. Aktuální formuláře se dají renderovat do bootstrapu hodně jednoduše.

https://github.com/nette/examples/blob/f9845422d4923bd5071ad586f24275c0737ee9ca/Forms/bootstrap3-rendering.php

**Comment by B4nan** [comment]
jo tohle sem samozrejme videl. no me slo ve finale hlavne o ty macra (jmenovite na {pair} jsem si fakt zvyknul). doplnim si je tedy sam :]
