### ISSUE TITLE
Not possible to install over composer

### ISSUE THREAD

**Issue by ghost** [Kdyby/BootstrapFormRenderer#37]
Problem 1
    - Installation request for kdyby/bootstrap-form-renderer dev-master -> satis
fiable by kdyby/bootstrap-form-renderer[dev-master].
    - kdyby/bootstrap-form-renderer dev-master requires nette/nette ~2.1@dev ->
no matching package found.

**Comment by fprochazka** [comment]
Chyba znamená že nenašel nette balíček ve verzi `2.1.*`, což je blbost. Zkus to znovu.

**Comment by enumag** [comment]
Tohle se někdy stává pokud máš v composer.json nette/nette s jiným version constraintem než 2.1

**Comment by ghost** [comment]
Hmm, to je zajímavé. Ted to jde a to jsem to předtím zkoušel několikrát.
